import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="body-inner-wrapper relative">
          <div className="header-section fixed top-0 left-0 w-full h-20 border-2 border-black">
            <h2>{"HEADER"}</h2>
          </div>
          <div className="footer-section fixed bottom-0 left-0 w-full h-20 border-2 border-black">
            <h2>{"NAV"}</h2>
          </div>
          <div className="details-card fixed bottom-0 left-0 w-full h-10 border-2 border-black">
            <h2>{"DETAILS CARD"}</h2>
          </div>
          <div className="main-wrapper absolute top-0 left-0 my-20 w-full border-2 border-red-400 -z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
